### ISSUE TITLE
Contribute to fortran-lang.org

### ISSUE THREAD

**Issue by LKedward** [tkoenig1/coarray-tutorial#2]
Dear Thomas @tkoenig1, this is a really nice introduction to coarrays. We're [looking for tutorials](https://github.com/fortran-lang/fortran-lang.org/issues/112) like this for <https://fortran-lang.org/learn>. Would you perhaps be willing to contribute a fortran-lang ['mini-book'](https://github.com/fortran-lang/fortran-lang.org/blob/master/MINIBOOKS.md) using this content, or permit someone else to do so?

**Comment by tkoenig1** [comment]
Hi Laurence @LKedward ,

I put the MIT license on this little project precisely for this sort of reason, because I wanted people to be able to use this.

So. if you want to include this in the minibook project by reference, or via a fork, both is fine by me.

**Comment by LKedward** [comment]
Brilliant! I'll close this issue and look to fork this with attribution onto the fortran-lang website in the future.
