### ISSUE TITLE
add fortran-tutorial tag

### ISSUE THREAD

**Issue by Beliavsky** [tkoenig1/coarray-tutorial#3]
Could you add the tag fortran-tutorial to your project? If all relevant repos add this tag it will make such material easier to find on GitHub. Currently topics such javascript-tutorial and python-tutorial have many entries.

**Comment by tkoenig1** [comment]
I'm not much of a GitHub expert. Did I do this correctly?

**Comment by Beliavsky** [comment]
No, the tag should appear in the About section, as done [here](https://github.com/Beliavsky/FortranTip). When done correctly your repo will appear [here](https://github.com/topics/fortran-tutorial).

**Comment by tkoenig1** [comment]
Got it, thanks!
